[project]
# Project name. This is used for output file naming only
ProjectName = Test

[io]
# Path to the file containing document IDx and annotation assignments
# See README.md for information on how this should be formatted
AssignmentsFilePath = ./data/annotator_assignments.csv

# Path to documents file. The annotation tool will
# search here first for a valid path. If this field 
# is left blank, then the tool will attempt to pull
# documents based on the DocumentsTable field below.
DocumentsFilePath = 

# Name of the data base table containing the text documents
DocumentsTable = alz_irb00312147.scratch_phi.annotation_test_documents

# Name of the document ID column in DocumentsTable
DocumentIDColumn = document_id

# Name of the document text column in DocumentsTable
DocumentTextColumn = document

# Path to an outputs directory. This is where annotations 
will be saved. NOTE: If the annotation notebook is placed 
# in a shared directory, make sure that the outputs 
# directory is also shared.
OutputDirPath = ./outputs/

[document.labels]
# This section defines the document-level labeling schema.
# Each line in this section will display as a tab with
# buttons for each possible value. Each row should have
# the format <label name> = <pipe>|<delimited>|<values>.

# "Label 1" is the label name and the values "a", "b", "c", 
# and "d" are the pipe delimited values
Label 1 = a|b|c|d

# "Label 2" is the label name and the values "e", "f", and "g" 
# are the pipe delimited values
Label 2 = e|f|g